### ISSUE TITLE
The theme docs imply that you have to list your theme in a common registry

### ISSUE THREAD

**Issue by michaellenaghan** [typlog/issues#17]
The [theme docs](https://docs.typlog.com/en/article/submit-theme/) say:

> Typlog hosts all themes on GitHub. To list your theme in Typlog theme registry, you need to create a pull request to add your theme into registry.json file.

That doesn't seem ideal?

I was thinking of taking two of the existing themes, and tweaking them. But I'm tweaking them for my particular needs; that isn't quite the same thing as creating themes for others to use.

In addition, I can think of possible problems. Here are two examples.

First, I may have some content in a site footer that's specific to my site. Typlog doesn't have a parameterization mechanism at the site level that would allow me to enter the info in the admin (the way, say, tags allow you to add arbitrary meta values), so I'd probably hard-code that content directly into the footer itself. (I can give specific examples of what I might put there.) Using HTML injection *might* be an alternative, but it would be an alternative that introduced its own problems. For example, that would only work for content at the very, very bottom of the page.

Second, on one of the themes I might use a font that I've purchased. If I do, I was going to put the font files on a CDN so that I could access them by URL from the template. The problem is that the font is licensed to me; I don't have the right to let others use it. Again, HTML injection *might* be an alternative, but it would be a slightly awkward one; the CSS, for example, would reference a font family that other users wouldn't have.

Those are two examples, but I can think of others.

It seems like there should be some mechanism that lets you use a custom theme without adding it to the list? For example: what if you could optionally enter a Github repository name directly?

**Comment by michaellenaghan** [comment]
Btw, `serve-theme` works very well. Very clever idea!

**Comment by lepture** [comment]
@michaellenaghan I'll allow pro site to use their own GitHub repo soon. It will take some time.

### custom font

As you mentioned, for custom font, you can add the font css link with HTML injection, and then re-define the font css variables:

for instance, in ueno:

```css
:root {
    --un-f-sys-sans: -apple-system, "Segoe UI", Oxygen, Ubuntu, "Droid Sans", "Helvetica Neue";
    --un-f-sys-serif: "Times New Roman", Georgia, Palatino, Times;
    --un-f-cjk: "PingFang SC", "Hiragino Sans GB", "Droid Sans Fallback", "Microsoft YaHei";
    --un-f-mono: Menlo, Monaco, Consolas, "Courier New", monospace;
    --un-f-base: var(--un-f-sys-sans), var(--un-f-cjk), sans-serif;
    --un-f-heading: var(--un-f-sys-sans), var(--un-f-cjk), sans-serif;
}
.yue {
    --yue-f-base: merriweather, var(--un-f-sys-serif), var(--un-f-cjk), serif;
    --yue-f-quote: var(--yue-f-base);
    --yue-f-heading: var(--un-f-heading);
    --yue-f-mono: var(--un-f-mono);
}
```

You can custom those CSS variables with HTML injection.

### footer content

The foot HTML injection will be located at the very bottom of the page. But if you want to add it somewhere else, it can be done with JavaScript. You can inject some JS to insert the HTML code.

Take an example, https://blog.authlib.org/2020/fastapi-google-login I added a HTML injection to add carbonads.
